### ISSUE TITLE
2 erreors, in frontend full movie view and in backend soundtrack manager

### ISSUE THREAD

**Issue by lion01** [Globulopolis/kinoarhiv#17]
hello,
I got two errors after installing the latest version available from github
when I try to access the soundtrack management page I get the following error as is visible in picture 1 (in backend) database table _ka_music_rel_movies' doesn't exist
And in frontend -> view full movie, there is another error in the voting tool
![database](https://cloud.githubusercontent.com/assets/5323019/5955081/4aba418c-a79f-11e4-991d-dd73cb7c7a7d.png)
![full movie view](https://cloud.githubusercontent.com/assets/5323019/5955085/562ec10a-a79f-11e4-9aee-50718c5bbce5.png)

**Comment by Globulopolis** [comment]
Soundtracks currently in development state.
