### ISSUE TITLE
Сортировка в Премьерах в админке

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#31]
Прошу сделать сортировку в Премьерах (в админке)
- [ ] по дате выхода в прокат - ЭТОТ ПУНКТ САМЫЙ ВАЖНЫЙ
- [ ] по ID
- [ ] по названию

**Comment by Globulopolis** [comment]
Уточните про сортировку, т.к. непонятно о чем речь. Сортировка по указанным пунктам работает.

**Comment by usmailer** [comment]
Яная сортировка есть только для Категории - Фильмы. 

"Сортировка фильмов - 
Сортировка будет произведена так же как в панели управления списком фильмов, но с учетом этих параметров."

на Категорию - Премьеры нужно отдельную сделать, т.к. у пользователя нет возможности сделать их разными...

с вводом новой возможности создания пользователем своих Категорий, было бы удобно сделать в каждой создаваемой категории вожность сортировать ее содержимое независимо от Глобальных настроек. Как это собственно сделано в обычных Категориях Джумлы.
Прошу рассмотреть внедрение этой фунции.

**Comment by Globulopolis** [comment]
Ясно. Добавлю сортировку в настройках.

**Comment by Globulopolis** [comment]
Посмотрел, подумал и решил - нет надобности. Премьеры и релизы сортируются на фронтенде по дате выхода по убыванию(т.е. самые последние(свежие) первыми). Нет смысла их сортировать как-то иначе. Тем более на забугорных ресурсах так же сортировка по дате.
