### ISSUE TITLE
Отключение голосования и рейтингов

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#34]
Прошу продумать чекбокс для отключения всех имеющихся функция голосования и рейтингов, т.к. не каждый ресурс позволяет регистрироваться участникам.

**Comment by Globulopolis** [comment]
Нужно ли делать возможность переназначения этих параметров для каждого фильма в отдельности или оставить только глобально?

**Comment by usmailer** [comment]
здесь на ваше усмотрение, если есть время и возможность, то лучше продумать и создать расширенный вариант этой функции, т.е. для каждого Каталога и каждого Фильма. Это задел на будущее, лишним не будет точно. Глобально так же должно быть.
