### ISSUE TITLE
Слетает настройка компонента

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#36]
при обновлении с 3.0.4 на 3.0.6 слетает настройка:
- чекбокс  - Разрешить голосование - переводится в положение ВКЛ
это скорее всего от появления в админке пункта - Отображение рейтинга

**Comment by Globulopolis** [comment]
Это не ошибка. Т.к. в 3.0.4 не было этого пункта, соответственно при появлении нового, береться значение по умолчанию установленное в `config.xml`.
