### ISSUE TITLE
цвета шаблона frontend и backend

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#37]
Прошу добавить в админке, рядом с выбором шаблона ссылку на место, где можно раздобыть другие цветовые схемы))
а так же, возможно во всплывающей подсказке, указать место хранения шаблонов на сервере.

это будет удобно и гораздо проще, чем включать некоторое количество в сам шаблон, увеличивая его вес...

**Comment by Globulopolis** [comment]
Поясните про какой шаблон идет речь? **Стиль компонента** или **Тема jQueryUI**?

**Comment by usmailer** [comment]
стиль компонента
тот что отображается на спойлерах в пользовательской части сайта.

**Comment by Globulopolis** [comment]
@usmailer это тема jqueryUI. http://jqueryui.com/resources/download/jquery-ui-themes-1.11.3.zip
В всплывающей подсказке - где лежит.
