### ISSUE TITLE
Количество элементов выводимых на фронтэнде

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#39]
Прошу рассмотреть создание инструмента по определению количества фильмов выводимых на фронтэнде.
на данный момент по умолчанию 20 шт.
портянка получается изрядная...
в общем достаточно стардартная разбивка на страницы...

- [x] 1. Список фильмов
- [x] 2. Список персон
- [x] 3. Список премьер
- [x] 4. Список релизов
- [ ] 5. ?

**Comment by Globulopolis** [comment]
Есть же выпадающий список с кол-вом элементов на страницу!?

**Comment by usmailer** [comment]
это пользовательский фильтр... а я предлагаю сделать административный инструмент... что бы по умолчанию можно было из админки давать количество... 
это конечно не критически важное добавление, но имеющее место быть в удобстве)

**Comment by Globulopolis** [comment]
Кол-во элементов в списке можно задать в настройках джумлы.

**Comment by usmailer** [comment]
согласен, но это же глобальные параметры для всего движка...
а речь идет о функционали конкретного компонента.

**Comment by Globulopolis** [comment]
Тепер нужно разобраться с тем, что и где переназначать.
1. Список фильмов.
2. Список персон.
3. Список премьер.
4. Список релизов.
5. ?

**Comment by usmailer** [comment]
не понял вопроса... но изначально задача - предоставить пользователю самому создавать Категории... а потом при создании Фильма - выбрать из списка ранее созданную Категорию.

**Comment by Globulopolis** [comment]
Я говорю про "Прошу рассмотреть создание инструмента по определению количества фильмов выводимых на фронтэнде."

**Comment by usmailer** [comment]
блин.. лошара)) не посмотрел... 
думаю, что это нужно делать для всех Категорий, которые могут появиться в компоненте...
ну и для существующих тоже нужно..  
т.е. все перечисленные 1-4 пункт и 5й - создаваемые Категории пользователем..
