### ISSUE TITLE
Проверка на дублирование вводимых данных

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#41]
Прошу ввести проверку на дублирование вводимых данных. В частности наименования Фильмов и Персон. Замечено - Персоны дублируются без всяких сложностей((

- [x] Профессии
- [x] Фильмы
- [x] Персоны
- [x] Жанры
- [x] Страны
- [x] Дистрибьюторы
- [x] Награды

**Comment by Globulopolis** [comment]
Все верно. Проверки на дублирование нет. В самой Joomla такой проверки нет, там просто к заголовку добавляется порядковый номер.
Надо подумать как правильно сделать.

**Comment by usmailer** [comment]
Очень бы хотелось... эту проверку... ибо когда тратишь время на заполнения данных - а потом оказывается что это дубль..  жалко времени.. да и путаница далее при выборе данных в карточке Фильма...
