### ISSUE TITLE
Вкл\откл вывода сортировки в Премьерах (и др.Категориях)

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#42]
Прошу продумать вожможность выбора в Админке компонента полей, для фильтрации содержимого Категории - Премьеры. На данный момент фильтры выводятся в пользовательской части - безусловно. 
Продумать простое отключение-включение данного блока полностью, одним чекбоксом например... а так же предоставление пользователю возможности самому выбирать нужные ему поля для фильтрации. Данне поля берутся из ранее введенных данных о фильме.

**Comment by Globulopolis** [comment]
Речь идет об этих фильтрах на фронтенде?
![untitled-1](https://cloud.githubusercontent.com/assets/740757/7001417/e76dee72-dc40-11e4-88ce-731db8a79bd9.jpg)

**Comment by usmailer** [comment]
да, именно про это...
ввести - вкл\выкл и собственный набор... фильтров...

**Comment by Globulopolis** [comment]
Сделано отключение существующих фильтров.
В собственном наборе фильтров нет смысла.
