### ISSUE TITLE
Загрузка трейлера

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#43]
Прошу проверить имеющуюся ошибку с загрузкой трейлера в формате МР4
получаю ошибку - Error: Invalid file extension: ИМЯ_ФАЙЛА.mp4

причем данный формат есть в сиписке Разрешенных.
причем при выборе папки с видеофайлом - его при выставленном фильтре "Все поддерживаемые типы фалов" - не видно.. приходится менять тип на "ВСЕ файлы" и тогда он появляется... но при попытке его заргузить - ошибка....

если заливать файл не средствами Компонента - по ФТП, то файл отлично размещается...

**Comment by Globulopolis** [comment]
Можете прислать этот файл на почту? Ил где его взять? Хочу mediainfo его посмотреть.

**Comment by usmailer** [comment]
вот к примеру...  - http://cache-spb05.cdn.yandex.net/kp.cdn.yandex.net/601933/kinopoisk.ru-Territoriya-242346.mp4

да не важно откуда.. с ютуба или с контакта... 
расширение мр4 не катит...

**Comment by Globulopolis** [comment]
Инфо о браузере в студию, а также скрин из настроек вот этого куска
![clipboard02](https://cloud.githubusercontent.com/assets/740757/7007809/80feb78e-dc95-11e4-9d1b-9cf365b14326.jpg)

**Comment by usmailer** [comment]
Firefox 37.0.1

![upload](https://cloud.githubusercontent.com/assets/11732559/7007872/2db179bc-dc96-11e4-8888-6be5f3519e7a.png)

**Comment by Globulopolis** [comment]
Странно. Попробуйте другой браузер.

**Comment by usmailer** [comment]
и что то мне подсказывает.. что не то я загружаю... все бразеры дают ошибку:
Интернет Эксплорер
![mp4_ie](https://cloud.githubusercontent.com/assets/11732559/7012336/30520c54-dcb9-11e4-902a-8079b235f0f1.png)
Опера
![mp4_opera](https://cloud.githubusercontent.com/assets/11732559/7012344/3f4d6b9a-dcb9-11e4-8092-72b9343bec8c.png)
Спартан (да.. у меня 10ка стоит) :)
![mp4_spartan](https://cloud.githubusercontent.com/assets/11732559/7012358/535922dc-dcb9-11e4-9465-526806264eba.png)

и стрелками указан момент... Это форма загрузки ИЗОБРАЖЕНИЯ
Соотв. я не вижу видеоформатов)))

**Comment by Globulopolis** [comment]
Эммм... Бывает :)
Там нужно подправить текст в сплывающей подсказке для иконки. А то непонятно загрузка чего там.

**Comment by usmailer** [comment]
хм.. а разве нет привязки загрузчика к указанным в админке форматам??
зачем тогда указывать разрешенные форматы?

**Comment by Globulopolis** [comment]
Привязка есть и проверка тоже. Но вы ж пытались :)

**Comment by usmailer** [comment]
отлично.. я то пытаюсь загрузить файл с форматом из списка фидеофайлов... 
а тут явное использование списка файлов изображений...
хотя должно быть видео...

**Comment by Globulopolis** [comment]
Загрузка видео, сабов и глав ниже в левой колонке.

**Comment by usmailer** [comment]
ок, тогда зачем справа вверху???

и все же как этим тогда пользоваться..нижней загрузкой.. 
я загрузил файл... он справа.. 
убрал код, как написано, что если загружен файл, то что то одно должно пользоваться... 
и на странице фильма нет трейлера...

может еще что то надо написать?

**Comment by usmailer** [comment]
![upload2](https://cloud.githubusercontent.com/assets/11732559/7018841/3399b598-dd12-11e4-96ee-da699f555b71.png)

**Comment by Globulopolis** [comment]
> ок, тогда зачем справа вверху???

Для скриншота.

> может еще что то надо написать?

Проверьте путь к ffmpeg и ffprobe. Без них работать не будет.

**Comment by usmailer** [comment]
ну неплохо бы тогда там сделать заголовок данного блака)))

кстати.. как я понимаюю там делается скриншоты автоматически из загружаемого видео??
или я ошибаюсь?

какие пути должны быть и где они?? где их проверять?

**Comment by Globulopolis** [comment]
Да. При загрузке видео, компонент сам делает скриншот с видео, но можно и переделать или загрузить свой. Собственно для этого и предназначена та кнопочка :)

Пути в настройках компонента -> Пути к каталогам - два первых поля.

**Comment by usmailer** [comment]
на месте все.. и права норм вроде...

путь - /var/www/kino/bin/ffmpeg/

а вот содержание:
![codec](https://cloud.githubusercontent.com/assets/11732559/7024087/f54fcbfc-dd42-11e4-865f-edd1b0ca6714.png)

**Comment by Globulopolis** [comment]
@usmailer у вас платформа какая? Windows или *nix?
Если *nix(а судя по пути) у вас именно эта платформа, вам ничем не поможет ffmpeg с скриншота.
Установите под вашу платформу и укажите к нему путь.

**Comment by usmailer** [comment]
ok)))
