### ISSUE TITLE
Загрузка саундтрека

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#44]
при попытке загрузить Саундтрек получаю - 
![soundtrack](https://cloud.githubusercontent.com/assets/11732559/7001992/102d197c-dc4c-11e4-9941-e2161cbfcfef.png)

компонент 3.0.6

Информация о системе
Параметр 	Значение
 
Платформа, на которой работает PHP 	Linux pul3-hq-web02 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64
Версия базы данных 	5.5.41-0+wheezy1
Кодировка базы данных 	cp1251_general_ci
Версия PHP 	5.4.39-0+deb7u2
Веб-сервер 	Apache/2.2.22 (Debian)
Интерфейс между веб-сервером и PHP 	apache2handler
Версия Joomla! 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Версия Joomla! Platform 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Браузер пользователя 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0

**Comment by Globulopolis** [comment]
Скажу по секрету - раздел "Саундтреки" вообще не готов.

**Comment by usmailer** [comment]
бугагагагаг))))

**Comment by Globulopolis** [comment]
Ну вот как-то так :) На все времени не хватает :)
