### ISSUE TITLE
Дистрибьютеры и привязка к языку.

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#45]
после обновление до 3.0.6. точно слетели ранее внесенные руками Дистрибьютеры.
Я точно добавлял "Двадцатый век фокс", после обновы его нет... даже в базе напрямую искал..

а так же нет Русского языка в Фильтрах "по языку".
![vendors2](https://cloud.githubusercontent.com/assets/11732559/7002103/e1c8f9a0-dc4d-11e4-86c6-41f229900e86.png)

в базе данных так же поле языка - "не определено"
![vendors1](https://cloud.githubusercontent.com/assets/11732559/7002105/ea50b752-dc4d-11e4-9245-069b4782ef82.png)

**Comment by Globulopolis** [comment]
В 3.0.5 обновление вносит изменения в таблицу дистрибьюторов. Предварительно таблица очищается.

**Comment by usmailer** [comment]
ужас..  а если там много дописок пользователя??  и как теперь восстановить  в уже созданных Фильмах???

**Comment by Globulopolis** [comment]
Первое правило обновлений - делайте бэкап.
"Не определено" означает что язык для этой записи не указан. Исправить можно через "Пакетная обработка".

**Comment by Globulopolis** [comment]
В уже созданных фильмах привязку поменять на данный момент нельзя. Вечером добавлю в пакетную обработку возможность менять некоторые поля пачкой.

**Comment by usmailer** [comment]
бекап сделан))) не в нем дело...
 после него  уже многое сделано...

в пакетной обработке нет Русского языка
![lang](https://cloud.githubusercontent.com/assets/11732559/7003323/25a6858a-dc61-11e4-9305-39c65f3afba4.png)

**Comment by Globulopolis** [comment]
Проверьте другие разделы и Пакетную обработку" на наличие русского языка.

**Comment by usmailer** [comment]
В странах тоже самое, нет привязки к языку и не в Пакетном его..
В Жанрах тоже самое...

**Comment by Globulopolis** [comment]
В Менеджере материалов есть?

**Comment by usmailer** [comment]
в Джумловском - Менеджер материалов: нет русского...
но все метериалы имеют значение Язык - ВСЕ

видимо берется системная переменная по выводу списка языков...

**Comment by Globulopolis** [comment]
> в Джумловском - Менеджер материалов: нет русского...
значит проблема в Джумле. Посмотрите в Менеджере языков что у вас.
