### ISSUE TITLE
Использование локальных путей  для размещения видеофайлов

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#46]
прошу реализовать возможность использования локальных путей на сервере для размещения, в частности, видеофайлов трейлеров..
исходная точка - корневая папка сайта

![199b7-clip-90kb](https://cloud.githubusercontent.com/assets/11732559/7176002/13feceb8-e423-11e4-9e2c-1b2713e9ce5d.png)

**Comment by Globulopolis** [comment]
Там просто валидация URL идет. Наверное прийдется убрать её.

**Comment by usmailer** [comment]
ну это на ваше усмотрение.. влом реально каждый раз писать полный адрес...

**Comment by Globulopolis** [comment]
Исправлено. Можете заменить файл у себя этим https://github.com/Globulopolis/kinoarhiv/blob/master/administrator/components/com_kinoarhiv/views/mediamanager/tmpl/default_upload_trailer.php
