### ISSUE TITLE
Добавление неизвестного Дистрибьютора

### ISSUE THREAD

**Issue by usmailer** [Globulopolis/kinoarhiv#47]
Прошу продумать и создать возможность при добавлении Дистрибьютора (а так же Профессии..Страны.. Жанра и т.д.) прямо в модальном окне ввода данных...

пример:
![fdb9f-clip-95kb](https://cloud.githubusercontent.com/assets/11732559/7176360/4e00f0de-e426-11e4-81ea-3ec2775c79ec.png)

т.е. когда создается Премьера, а нужного Дистрибьютора нет в базе, нужно закрыть это окно создания Премьеры... покинуть карточку заполняемого Фильма, пойти в меню - Компоненты.. выбрать - Дистрибьютеров и только потом Создать его... 
далее нужно вернуться в карточку фильма и заново выбрать только что созданного Дистрибьютора..

как это вижу я:
при вводе идет поиск имеющихся значений, если нет искомого - появляется тут же кнопка - Добавить...
и вызывается поверх имеющего окна - окно добавления Нового Дистрибьютора.. с уже вставленной в поле Имя ранее введенными данными.
после заполнения обязательных полей - Сорхранить и закрывается окно добавления Нового Дистрибьютора. 
Данные - Имя Дистрибьютора - автоматически всталяются в нужные поля создаваемой Новой Премьеры.

**Comment by Globulopolis** [comment]
Добавил форму для дистрибьюторов.
По поводу
> (а так же Профессии..Страны.. Жанра и т.д.)

подробнее можно? Где именно?

**Comment by usmailer** [comment]
прошу прощения.. выходные... СКА Чемпион и все такое)))

позвольте продолжить ответом..
при редактировании карточки Фильма во вкладке - "Создатели фильма, роли" добавляя Персону - не получается ее сохранить..
см.скрин
![persona](https://cloud.githubusercontent.com/assets/11732559/7224983/dd9a5672-e741-11e4-986f-fbbdafdbca17.png)
все поля заполняю.. получаю кнопу - Сохранить.. и в итоге нет того Персонажа, которого я записывал..
С - Профессиями - проблем нет.. там все записывается... 
может это конечно у меня что то персональьно сломано...

**Comment by Globulopolis** [comment]
Случайно с гита не обновляли? Сегодня гляну что не так.

**Comment by usmailer** [comment]
нет.. релиз 3.0.6

**Comment by Globulopolis** [comment]
Релиза ещё не было. Временно сломано сохранение персон.

**Comment by usmailer** [comment]
как небыло??? вот он же.. скачать же можно....

**Comment by Globulopolis** [comment]
На гите в мастере версия для разработки. Финальные я выкладываю отдельно.

**Comment by usmailer** [comment]
хорошо, жду релиза следующего.. и особенно функции отключения покаа фильма и переноса в другие категории..

**Comment by Globulopolis** [comment]
Исправил ошибку с сохранением персон в форме быстрого добавления.

**Comment by usmailer** [comment]
спасибо
